//Filters
export const ADD_LOCATION_FILTER = "ADD_LOCATION_FILTER";
export const ADD_LOCATIONTYPE_FILTER = "ADD_LOCATIONTYPE_FILTER";
export const ADD_COMMON_FILTER = "ADD_COMMON_FILTER";
export const REMOVE_LOCATION_FILTER = "REMOVE_LOCATION_FILTER";
export const REMOVE_LOCATIONTYPE_FILTER = "REMOVE_LOCATIONTYPE_FILTER";
export const REMOVE_COMMON_FILTER = "REMOVE_COMMON_FILTER";
export const REMOVE_ALL_LOCATIONTYPE_FILTERS = "REMOVE_ALL_LOCATIONTYPE_FILTERS";
export const REMOVE_ALL_COMMON_FILTERS = "REMOVE_ALL_COMMON_FILTERS";
export const UPDATE_FETCHED_FILTERS = "UPDATE_FETCHED_FILTERS";
export const UPDATE_FETCHED_AREAS = "UPDATE_FETCHED_AREAS";


//search
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const UPDATE_RESULTS = "UPDATE_RESULTS";
export const FETCH_NON_ACCEPTED = "FETCH_NON_ACCEPTED";
export const PREVIOUS_FILTER = "PREVIOUS_FILTER";
//login
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";

//general
export const SET_LANGUAGE = "SET_LANGUAGE";
export const LOADING = "LOADING"

//map
export const SET_COORDINATES = "SET_COORDINATES";
export const SELECT_LOCATION = "SELECT_LOCATION";
export const RESET_LOCATION = "RESET_LOCATION";
export const SELECT_MHEADER_LOCATION = "SELECT_MHEADER_LOCATION";
export const RESET_MHEADER_LOCATION = "RESET_MHEADER_LOCATION"
