//Filters
export const ADD_LOCATION_FILTER = "ADD_LOCATION_FILTER";
export const ADD_LOCATIONTYPE_FILTER = "ADD_LOCATIONTYPE_FILTER";
export const ADD_COMMON_FILTER = "ADD_COMMON_FILTER";
export const REMOVE_LOCATION_FILTER = "REMOVE_LOCATION_FILTER";
export const REMOVE_LOCATIONTYPE_FILTER = "REMOVE_LOCATIONTYPE_FILTER";
export const REMOVE_COMMON_FILTER = "REMOVE_COMMON_FILTER";
export const REMOVE_ALL_LOCATIONTYPE_FILTERS = "REMOVE_ALL_LOCATIONTYPE_FILTERS";
export const REMOVE_ALL_COMMON_FILTERS = "REMOVE_ALL_COMMON_FILTERS"

//search
export const FETCH_LOCATIONS = "FETCH_LOCATIONS";
export const UPDATE_RESULTS = "UPDATE_RESULTS";
